// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUJBgzGkgXlEvkKEalNpNe6RczscoDwr8',
    appId: '1:438484145708:web:88a5815371398344176389',
    messagingSenderId: '438484145708',
    projectId: 'app-7room',
    authDomain: 'app-7room.firebaseapp.com',
    storageBucket: 'app-7room.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA4jU_5FbA9B67XPmxCxCC5Zq8J_EvDZs',
    appId: '1:438484145708:android:76a79ce42ceabcc9176389',
    messagingSenderId: '438484145708',
    projectId: 'app-7room',
    storageBucket: 'app-7room.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIjwaM7htr-__SP2u7f7E4FITRRALdv1Q',
    appId: '1:438484145708:ios:74fb2ace72983d32176389',
    messagingSenderId: '438484145708',
    projectId: 'app-7room',
    storageBucket: 'app-7room.firebasestorage.app',
    iosClientId: '438484145708-qt7ku78sqa4plge4oenijh6319oosgmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.app7room',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIjwaM7htr-__SP2u7f7E4FITRRALdv1Q',
    appId: '1:438484145708:ios:74fb2ace72983d32176389',
    messagingSenderId: '438484145708',
    projectId: 'app-7room',
    storageBucket: 'app-7room.firebasestorage.app',
    iosClientId: '438484145708-qt7ku78sqa4plge4oenijh6319oosgmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.app7room',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUJBgzGkgXlEvkKEalNpNe6RczscoDwr8',
    appId: '1:438484145708:web:5ea366cfe1004a0e176389',
    messagingSenderId: '438484145708',
    projectId: 'app-7room',
    authDomain: 'app-7room.firebaseapp.com',
    storageBucket: 'app-7room.firebasestorage.app',
  );

}