// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY1GDIgRSbHpz4QMkcjoe1lK_bemJ8rH4',
    appId: '1:713750447434:web:1265a60657a6c61669adb3',
    messagingSenderId: '713750447434',
    projectId: 'sevenroom-a',
    authDomain: 'sevenroom-a.firebaseapp.com',
    storageBucket: 'sevenroom-a.firebasestorage.app',
    measurementId: 'G-CMNG6KECZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKqqrGNbvqgpyXyu-98KNqQwA_MyGdCio',
    appId: '1:713750447434:android:193468e2a213a34169adb3',
    messagingSenderId: '713750447434',
    projectId: 'sevenroom-a',
    storageBucket: 'sevenroom-a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPz2pa4A6aePkftZ65zou4wfmbg3X_OpU',
    appId: '1:713750447434:ios:4e90b67fe8501c0969adb3',
    messagingSenderId: '713750447434',
    projectId: 'sevenroom-a',
    storageBucket: 'sevenroom-a.firebasestorage.app',
    iosClientId: '713750447434-v38c2fhmsvstj334agiotda66fs1pv14.apps.googleusercontent.com',
    iosBundleId: 'com.example.app7room',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPz2pa4A6aePkftZ65zou4wfmbg3X_OpU',
    appId: '1:713750447434:ios:4e90b67fe8501c0969adb3',
    messagingSenderId: '713750447434',
    projectId: 'sevenroom-a',
    storageBucket: 'sevenroom-a.firebasestorage.app',
    iosClientId: '713750447434-v38c2fhmsvstj334agiotda66fs1pv14.apps.googleusercontent.com',
    iosBundleId: 'com.example.app7room',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY1GDIgRSbHpz4QMkcjoe1lK_bemJ8rH4',
    appId: '1:713750447434:web:65301317fe985a7369adb3',
    messagingSenderId: '713750447434',
    projectId: 'sevenroom-a',
    authDomain: 'sevenroom-a.firebaseapp.com',
    storageBucket: 'sevenroom-a.firebasestorage.app',
    measurementId: 'G-TCF8G1NJDX',
  );
}
